# Generated by Django 3.0.8 on 2021-04-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210405_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bad_msg_count',
            field=models.IntegerField(default=0),
        ),
    ]
