# Generated by Django 3.0.8 on 2021-02-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_auto_20201120_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
