# Generated by Django 3.0.8 on 2021-04-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210405_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bad_word_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nude_count',
        ),
    ]
