# Generated by Django 3.0.8 on 2020-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201104_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_like',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], default='like', max_length=10),
        ),
    ]
