# Generated by Django 3.0.8 on 2021-04-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210405_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
