# Generated by Django 3.0.8 on 2020-11-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201104_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_like',
            new_name='like_value',
        ),
    ]
