# Generated by Django 3.0.8 on 2020-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200806_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
