# Generated by Django 3.0.8 on 2020-11-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201104_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_value',
            new_name='value',
        ),
    ]
